version: '3'

services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3308:3308'
    volumes:
      - ./tmp/db:/var/lib/mysql

  app:
    build: .
    container_name: rails_base
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3002:3002'
    depends_on:
      - db