version: '3'

services:
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3309:3306'
    volumes:
      - ./tmp/db:/var/lib/mysql

  app:
    build: .
    container_name: perfect_ruby_on_rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3005 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - '3005:3005'
    depends_on:
      - db